# General configuration
general:
  run_name: "generation_watermark_longform_qa_llama3_unigram"

# Model configuration
model:
  name: "meta-llama/Meta-Llama-3-8B-Instruct"
  kwargs:
    dtype: "float16"
    device_map: "auto"
  transformers_config_kawrgs: {}

# Watermarking parameters
watermark:
  active: true
  algorithm_name: "Unigram"
  generation_kwargs:
    use_chat_template: true

# Generation parameters
generation:
  save_every: 25
  max_samples: null
  n_generations_per_sample: 3

# File configuration
file:
  root_dir: "PUPPET/experimental"
  input:
    benchmark: "waterbench"
    dataset: "longform_qa"
  output:
    path: "watermark_gen/data"