general:
  run_name: "shap_longform_qa_vanila_llama3"

shap:
  models:
    openai:
      kwargs: {}
  preprocess: {}
  max_samples: null

file:
  root_dir: "PUPPET/experimental"
  generation:
    path: "vllm_gen/data/baselines/vanila/generation_vllm_longform_qa_llama3_dpo_baseline_2025_1204_141800.jsonl"
    field: "vllm_model_output"
  output:
    path: "shap_analysis/results"