# General configuration
general:
  run_name: "evaluation_watermark_longform_qa_llama3_expgumbel_paraphrased"

# Evaluation configuration
evaluation:
  metrics:
    rouge_score_waterbench:
      reference:
        path: "paraphrase/results/paraphrase_watermark_longform_qa_llama3_expgumbel_2026_0130_141853.jsonl"
        field: "outputs"
    detect_openai:
      kwargs:
        detector_kwargs:
          device_map: "auto"
  preprocess: {}
  max_samples: null

# File configuration
file:
  root_dir: "PUPPET/experimental"
  generation:
    path: "paraphrase/results/paraphrase_watermark_longform_qa_llama3_expgumbel_2026_0130_141853.jsonl"
    field: "paraphrase_outputs"
  output:
    path: "evaluation/results"