# General configuration
general:
  run_name: "paraphrase_ielts_human"

# Paraphrase configuration
paraphrase:
  model_kwargs:
    dtype: "float16"
  generation_kwargs:
    lex_diversity: 60
    order_diversity: 60
    do_sample: true
    top_p: 0.75
    top_k: null
    max_length: 512
  preprocess: []
  max_samples: null

# File configuration
file:
  root_dir: "PUPPET/experimental"
  generation:
    path: "dpo_data/data/ielts_preprocessed_random_200_test_202601161730_human_answers.jsonl"
    field: "outputs"
  output:
    path: "paraphrase/results"