# General configuration
general:
  run_name: "detection_watermark_longform_qa_llama3_unigram_paraphrased"

# Model configuration
model:
  name: "meta-llama/Meta-Llama-3-8B-Instruct"
  vocab_size: 128256
  transformers_config_kawrgs: {}

# Watermark configuration
watermark:
  algorithm_name: "Unigram"
  generation_kwargs: {}

# File configuration
file:
  root_dir: "PUPPET/experimental"
  generation:
    path: "paraphrase/results/paraphrase_watermark_longform_qa_llama3_unigram_2026_0130_134716.jsonl"
    field: "paraphrase_outputs"
    extract:
      method: "flatten"
      kwargs: {}
    preprocess: []
  output:
    path: "watermark_det/results"
