# General configuration
general:
  run_name: "detection_watermark_longform_qa_qwen3_unigram"

# Model configuration
model:
  name: "Qwen/Qwen3-8B"
  transformers_config_kawrgs: {}

# Watermark configuration
watermark:
  algorithm_name: "Unigram"
  generation_kwargs: {}

# File configuration
file:
  root_dir: "PUPPET/experimental"
  generation:
    path: "watermark_gen/data/baselines/unigram/generation_watermark_longform_qa_qwen3_unigram_2026_0129_140046.jsonl"
    field: "watermarked_model_output"
    extract:
      method: flatten
      kwargs: {}
    preprocess:
      - name: "extract_answer_with_regex"
        kwargs:
          regex_pattern: 'assistant\s*\n<think>\s*\n\s*</think>\s*\n\s*(.*)$'
  output:
    path: "watermark_det/results"
