# General configuration
general:
  run_name: "evaluation_vllm_ielts_llama3_dpo_baseline_paraphrased"

# Evaluation configurationevaluation:
evaluation:
  metrics:
    llm_as_a_judge:
      reference:
        path: "paraphrase/results/paraphrase_vllm_ielts_llama3_dpo_baseline_2026_0120_172439.jsonl"
        field: "context"
      kwargs:
        model:
          name: "openai/gpt-oss-20b"
          kwargs:
            dtype: "auto"
            gpu_memory_utilization: 0.45
            tensor_parallel_size: 1
        chat_template_kwargs: {}
        thinking_kwargs:
          stop: ["<|start|>assistant<|channel|>final<|message|>"]
          temperature: 0.0
          max_tokens: 4096
        scoring_kwargs:
          temperature: 0.0
        score_prefix: "Score: "
        score_labels: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
        prompt: "evaluation/materials/llm_as_a_judge_prompts/ielts.txt"
        max_retries: 20
        judge_outputs_dir: "evaluation/results/temporary"
        judge_outputs_path: null
        use_chat_template: true
    detect_openai:
        kwargs:
          detector_kwargs:
            device_map: "auto"
  preprocess: []
  max_samples: null

# File configuration
file:
  root_dir: "PUPPET/experimental"
  generation:
    path: "paraphrase/results/paraphrase_vllm_ielts_llama3_dpo_baseline_2026_0120_172439.jsonl"
    field: "paraphrase_outputs"
  output:
    path: "evaluation/results"