# General configuration
general:
  run_name: "generation_vllm_outfox_qwen3_dpo_lrx100_drstd_5000_ckpt200"

# Model configuration
model:
  name: "Qwen/Qwen3-8B"
  lora_path: "PUPPET/experimental/dpo/checkpoints/training_outfox_qwen3_lrx100_drstd_5000_2025_1218_102308/checkpoint-200"
  kwargs:
    dtype: "float16"
    tensor_parallel_size: 1
  chat_template_kwargs:
    enable_thinking: false

# Generation parameters
generation:
  max_samples: null
  kwargs:
    n: 1
  chat_template_kwargs:
    enable_thinking: false

# File configuration
file:
  root_dir: "PUPPET/experimental"
  input:
    use_custom_dataset: true
    custom_dataset: "dpo_data/data/outfox_preprocessed_random_200_test_202512161348"
    benchmark: "outfox"
    dataset: "outfox"
  output:
    path: "vllm_gen/data"