# General configuration
general:
  run_name: "generation_vllm_multi_news_llama3_dpo_baseline"

# Model configuration
model:
  name: "meta-llama/Meta-Llama-3-8B-Instruct"
  kwargs:
    dtype: "float16"
    tensor_parallel_size: 1

# Generation parameters
generation:
  max_samples: null
  kwargs:
    n: 1

# File configuration
file:
  root_dir: "PUPPET/experimental"
  input:
    benchmark: "waterbench"
    dataset: "multi_news"
  output:
    path: "vllm_gen/data"