# General configuration
general:
  run_name: "evaluation_vllm_multinews_qwen3_dpo_lrx100_drstd_5000_ckpt1000"

# Evaluation configuration
evaluation:
  metrics:
    rouge_score_waterbench:
      reference:
        path: "vllm_gen/data/ours/ckpts/qwen3/multinews/generation_vllm_multinews_qwen3_dpo_lrx100_drstd_5000_ckpt1000_2026_0211_135903.jsonl"
        field: "outputs"
    detect_openai:
      kwargs:
        detector_kwargs:
          device_map: "auto"
  preprocess: {}
  max_samples: null

# File configuration
file:
  root_dir: "PUPPET/experimental"
  generation:
    path: "vllm_gen/data/ours/ckpts/qwen3/multinews/generation_vllm_multinews_qwen3_dpo_lrx100_drstd_5000_ckpt1000_2026_0211_135903.jsonl"
    field: "vllm_model_output"
  output:
    path: "evaluation/results"