# General configuration
general:
  run_name: "evaluation_watermark_multi_news_qwen3_4b_k-semstamp"

# Evaluation configuration
evaluation:
  metrics:
    rouge_score_waterbench:
      reference:
        path: "watermark_gen/data/generation_watermark_multinews_qwen3_4b_k-semstamp_2026_0323_131307.jsonl"
        field: "outputs"
  preprocess:
    - name: "extract_answer_with_regex"
      kwargs:
        full_output_field: "watermarked_model_output"
        regex_pattern: 'assistant\s*\n<think>\s*\n\s*</think>\s*\n\s*(.*)$'
  max_samples: null

# File configuration
file:
  root_dir: "PUPPET/experimental"
  generation:
    path: "watermark_gen/data/generation_watermark_multinews_qwen3_4b_k-semstamp_2026_0323_131307.jsonl"
    field: "watermarked_model_output"
  output:
    path: "evaluation/results"
