# General configuration
general:
  run_name: "detection_watermark_multi_news_llama3_synthid"

# Model configuration
model:
  name: "meta-llama/Meta-Llama-3-8B-Instruct"
  transformers_config_kawrgs: {}

# Watermark configuration
watermark:
  algorithm_name: "SynthID"
  generation_kwargs: {}

# File configuration
file:
  root_dir: "PUPPET/experimental"
  generation:
    path: "watermark_gen/data/baselines/synthid/generation_watermark_multi_news_llama3_2025_1220_161723_synthid.jsonl"
    field: "watermarked_model_output"
    extract:
      method: flatten
      kwargs: {}
    preprocess:
      - name: "extract_answer_with_regex"
        kwargs:
          regex_pattern: 'assistant\s*\n\s*\n(.*)$'
  output:
    path: "watermark_det/results"

# Device configuration
device:
  server: "hestia"
  type: "cuda"