# General configuration
general:
  run_name: "paraphrase_vllm_longform_qa_qwen3_dpo_multinews_lrx100_drstd_5000_mage"

# Paraphrase configuration
paraphrase:
  model_kwargs:
    dtype: "float16"
  generation_kwargs:
    lex_diversity: 60
    order_diversity: 60
    do_sample: true
    top_p: 0.75
    top_k: null
    max_length: 512
  preprocess: []
  max_samples: null

# File configuration
file:
  root_dir: "PUPPET/experimental"
  generation:
    path: "vllm_gen/data/ours/multi_detector/generation_vllm_longform_qa_qwen3_dpo_multinews_lrx100_drstd_5000_mage_2026_0320_124641.jsonl"
    field: "vllm_model_output"
  output:
    path: "paraphrase/results"
