# General configuration
general:
  project_name: "PUPPET"
  run_name: "training_ielts_qwen3_lrx100_drstd_5000_evaluator_score_only"

# Model configuration
model:
  name: "Qwen/Qwen3-8B"
  kwargs:
    dtype: "float16"
    device_map: "auto"

# Training parameters
training:
  dataset_kwargs:
    max_train_samples: null
    max_eval_samples: null
  use_lora: true
  lora_kwargs:
    target_modules: null
  dpo_kwargs:
    learning_rate: 1.0e-04
    beta: 0.1
    loss_type: "sigmoid"
    num_train_epochs: 1
    per_device_train_batch_size: 10
    logging_steps: 16
    save_strategy: "no"
    save_steps: null
    eval_strategy: "no"
    eval_steps: null
    per_device_eval_batch_size: null
    data_seed: 42
    max_length: 8192
    max_completion_length: 512
    generate_during_eval: false
    precompute_ref_log_probs: true
    remove_unused_columns: false

# File configuration
file:
  root_dir: "PUPPET/experimental"
  dataset: "PUPPET/experimental/dpo_data/data/ietls_detect_laaj_standarzied_5000_logprobs_ielts_evaluator_score_only_qwen3_202603210624"
  output:
    path: "dpo/checkpoints"
