# General configuration
general:
  run_name: "evaluation_watermark_multi_news_qwen3_kgw_paraphrased"

# Evaluation configuration
evaluation:
  metrics:
    rouge_score_waterbench:
      reference:
        path: "paraphrase/results/paraphrase_watermark_multi_news_qwen3_kgw_2026_0128_163401.jsonl"
        field: "outputs"
    detect_openai:
      kwargs:
        detector_kwargs:
          device_map: "auto"
  preprocess: {}
  max_samples: null

# File configuration
file:
  root_dir: "PUPPET/experimental"
  generation:
    path: "paraphrase/results/paraphrase_watermark_multi_news_qwen3_kgw_2026_0128_163401.jsonl"
    field: "paraphrase_outputs"
  output:
    path: "evaluation/results"